module.exports = [
  {
    name: 'Partymaker',
    email: 'bot@partymaker.zp.ua',
    phone: '+380555555555',
    password: 'qwerty123',
    avatar_url: '/images/logo_big.png',
    is_superadmin: true,
    is_active: true,
  },
  {
    name: 'Super Admin',
    email: 'admin@mailinator.com',
    phone: '+380683188524',
    password: 'qwerty123',
    avatar_url: '/images/dummy/pavliha.jpg',
    is_superadmin: true,
    is_active: true,
  },
  {
    name: 'Aleksey Lukovka',
    email: 'lukerlexa@gmail.com',
    phone: '+380990848975',
    password: '123123',
    avatar_url: '/images/dummy/aleksey.jpeg',
    is_superadmin: true,
    is_active: true,
  },
  {
    name: 'Аня Форостьюянова',
    email: 'aforostanova@gmail.com',
    phone: '+380971766908',
    password: 'qwerty123',
    avatar_url: '/images/dummy/anya.jpg',
    is_superadmin: true,
    is_active: true,
  },
  {
    name: 'Regular User',
    email: 'regular@mailinator.com',
    phone: '+380000000001',
    password: 'qwerty123',
    avatar_url: '/images/dummy/regular.png',
    is_superadmin: false,
    is_active: true,
  },
  {
    name: 'New User',
    email: 'new@mailinator.com',
    phone: '+380000000002',
    password: 'qwerty123',
    avatar_url: '/images/dummy/regular.png',
    is_superadmin: false,
    is_active: false,
  },
]
